### ISSUE TITLE
10.12.5 version of CoreDisplay and nVidia found

### ISSUE THREAD

**Issue by rdmitry0911** [Floris497/mac-pixel-clock-patch-V2#185]
Just updated my hackint0sh to 10.12.5 from 10.11.6, installed new web drivers and after that have this problem.
I tried both patch v2 and v3, none works for me. On my 4k monitor I have only 30Hz, while before update it was 60Hz
```
Unknown version of CoreDisplay found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     otool CoreDisplay: ecc61a550ebe819f63bdf3eb198e2d35
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: 5ebdbc42c414d053ae14f38f7601f1ba
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

Unknown version of the Nvidia driver found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     NVDAGK100Hal: 18a647b2070fa53ec186415757cf6334
 NVDAGK100Hal.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment]
What card do you have? I don't have a patch for Kepler WEB drivers now.. it should be easy to make tho

**Comment by rdmitry0911** [comment]
GTX 950

**Comment by Floris497** [comment]
Good take the maxwell web driver patch and use it like `filename.command patch v1`

**Comment by rdmitry0911** [comment]
No, doesn't work. I tried both

CoreDisplay-patcher.command patch v3 
NVIDIA-WEB-MAXWELL-patcher.command patch v1

and 

CoreDisplay-patcher.command patch v2
NVIDIA-WEB-MAXWELL-patcher.command patch v1

Neither one works. Still have only 30Hz available in switchresx

**Comment by Floris497** [comment]
I will have to look tomorrow.. but it should actually work with only CoreDisplay patch..

**Comment by rdmitry0911** [comment]
I checked CoreDisplay patch only, but it doesn't work also.

**Comment by rdmitry0911** [comment]
Nothing new today?

**Comment by Floris497** [comment]
CoreDisplay should be ran without any additions but v3 should work.. can you check MD5's for both by running `filename.command md5`

**Comment by rdmitry0911** [comment]
Here they are:

---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     NVDAGM100HalWeb: e351c25f7f11665b4c8b38675b7d3a51
 NVDAGM100HalWeb.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     otool CoreDisplay: 54a5a1adfb1225411bacf5c3ee0b4d9a
 otool CoreDisplay.bak: NO FILE (this is okay)
           CoreDisplay: 5ebdbc42c414d053ae14f38f7601f1ba
       CoreDisplay.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
Ah so nothing was patched at all..

**Comment by Floris497** [comment]
run the CoreDisplay like `CoreDisplay-patcher.command` and the Nvidia one like `NVIDIA-WEB-MAXWELL-patcher.command`

**Comment by rdmitry0911** [comment]
No, still not working. current md5 are below
---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     otool CoreDisplay: 8b876f14be2bf7b1bfd3f89341bce0f6
 otool CoreDisplay.bak: 54a5a1adfb1225411bacf5c3ee0b4d9a
           CoreDisplay: 62b589c841acb5233b8c0c8bac73a9c8
       CoreDisplay.bak: 5ebdbc42c414d053ae14f38f7601f1ba

---- ENDING MD5 HASH SUMS -------


---- BEGINNING MD5 HASH SUMS ---- version: 10.12.5 build:16F73

     NVDAGM100HalWeb: 059e81a8ffb42e41e57de6686a71d6e4
 NVDAGM100HalWeb.bak: e351c25f7f11665b4c8b38675b7d3a51

---- ENDING MD5 HASH SUMS -------

**Comment by rdmitry0911** [comment]
No news for today?

**Comment by Floris497** [comment]
I'm not sure.. if it did work in 10.11.6 I have no idea what can be wrong.. did you make a custom resolution?

**Comment by rdmitry0911** [comment]
Yes, in SwitchResX I did a custom resolution 3840 x 2160 @ 60Hz and in 10.11.6 this custom resolution is stated as active (and I have 4k@60Hz) and in 10.12.5 it is stated as not active and any attempts to apply this resolution fail. Here I collected some screenshots of SwitchResX windows in 10.12.5 and 10.11.6. 


[10.12.5.zip](https://github.com/Floris497/mac-pixel-clock-patch-V2/files/1050193/10.12.5.zip)
[10.11.6.zip](https://github.com/Floris497/mac-pixel-clock-patch-V2/files/1050194/10.11.6.zip)

**Comment by Floris497** [comment]
For 10.12.5 i only see a picture of 'not installed'

**Comment by rdmitry0911** [comment]
Yes, it is exactly what happening. SwitchResX doesn't allow me to activate this profile. When I press the apply now button, the screen is blinking couple of times (which I consider as trying to set a new mode) but remains the same after.

**Comment by Floris497** [comment]
So is it fixed now?

**Comment by rdmitry0911** [comment]
No, I still can't apply the 4k@60 Hz resolution. The screen is blinking, but remains at 4k@30Hz and a 4k@60Hz resolution does not appear in the possible resolutions list in SwitchResX

**Comment by Floris497** [comment]
Hm.. then i have no idea.. sorry

**Comment by rdmitry0911** [comment]
Is there a way to check, that the patch is applied the proper way? I mean, to check that the pixel clock restrictions are not effective anymore?

**Comment by Floris497** [comment]
Well.. when the setting shows up in switchresx and it is set to 'active' than the patch is either applied or you don't need it.. `filename.command status` you can see if the patch is applied or not.
